on: [push, pull_request]

name: cover

jobs:
  cover:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUBPAT }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: false
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: macOS-r-4.0-2-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: macOS-r-4.0-2-

      - name: Install Mac system dependencies
        run: |
          brew install jags

      - name: Install packages
        run: |
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE, type = "binary")
          remotes::install_cran("covr")
        shell: Rscript {0}

      - name: Test coverage
        run: covr::codecov(quiet = FALSE)
        shell: Rscript {0}
